name: Deployment workflow
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v1
      -
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      -
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: '${{ runner.os }}-node-${{ hashFiles(''**/package.json'') }}'
          restore-keys: "${{ runner.os }}-node-\n"
      -
        name: Install Dependency
        run: 'npm install'
      -
        name: Build dist
        run: 'npm run build'
      -
        name: Zip dist direction
        run: 'zip dist.zip ./dist/*'
      -
        name: Setup aliyun oss
        uses: manyuanrong/setup-ossutil@master
        with:
          endpoint: oss-cn-shenzhen.aliyuncs.com
          access-key-id: '${{ secrets.OSS_KEY_ID }}'
          access-key-secret: '${{ secrets.OSS_KEY_SECRET }}'
      -
        name: Copy files to aliyun OSS
        run: 'ossutil cp -rf ./dist/ oss://ship-manager-cdn/'
      -
        name: Copy dist file to server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ./dist.zip
          remote: /root/ship/remote/dist.zip
          username: root
          host: '${{ secrets.HOST }}'
          privateKey: '${{ secrets.PRIVATE_KEY }}'
