name: Deployment workflow
on: [push]
jobs:
  build-shipManager-webapp:
    name: build dist
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[build]')"
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 10.16
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn install
      - name: Build dist
        run: 'npm run build'
      - name: Zip dist direction
        run: 'zip dist.zip ./dist/*'
      - name: Setup aliyun oss
        uses: manyuanrong/setup-ossutil@master
        with:
          endpoint: oss-cn-shenzhen.aliyuncs.com
          access-key-id: '${{ secrets.OSS_KEY_ID }}'
          access-key-secret: '${{ secrets.OSS_KEY_SECRET }}'
      - name: Copy files to aliyun OSS
        run: 'ossutil cp -rf ./dist/ oss://ship-manager-cdn/'
      - uses: actions/upload-artifact@v1
        with:
          name: Dist Folder
          path: dist
